<?xml version="1.0" encoding="UTF-8"?>
<!--
  * registry/pressSettings.xml
  *
  * Copyright (c) 2014-2018 Simon Fraser University
  * Copyright (c) 2003-2018 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Default press settings.
  -->

<!DOCTYPE press_settings [
	<!ELEMENT press_settings (setting+)>
	<!ELEMENT setting (name, value)>
	<!ATTLIST setting type (int|string|object|bool) #REQUIRED>
	<!ATTLIST setting locale (0|1) #REQUIRED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT value (#PCDATA | array)*>
	<!ELEMENT element (#PCDATA | array)*>
	<!ATTLIST element key CDATA #IMPLIED>
	<!ELEMENT array (element+)>
]>

<press_settings>
	<setting type="int" locale="0">
		<name>coverThumbnailsMaxWidth</name>
		<value>106</value>
	</setting>
	<setting type="int" locale="0">
		<name>coverThumbnailsMaxHeight</name>
		<value>100</value>
	</setting>
	<setting type="int" locale="0">
		<name>numPageLinks</name>
		<value>10</value>
	</setting>
	<setting type="int" locale="0">
		<name>itemsPerPage</name>
		<value>50</value>
	</setting>
	<setting type="int" locale="0">
		<name>numWeeksPerReview</name>
		<value>4</value>
	</setting>
	<setting type="int" locale="0">
		<name>defaultReviewMode</name>
		<value>2</value><!-- SUBMISSION_REVIEW_METHOD_DOUBLEBLIND -->
	</setting>
	<setting type="int" locale="0">
		<name>numWeeksPerResponse</name>
		<value>3</value>
	</setting>
	<setting type="string" locale="1">
		<name>privacyStatement</name>
		<value>{translate key="default.pressSettings.privacyStatement"}</value>
	</setting>
	<setting type="string" locale="1">
		<name>openAccessPolicy</name>
		<value>{translate key="default.pressSettings.openAccessPolicy"}</value>
	</setting>
	<setting type="string" locale="0">
		<name>emailSignature</name>
		<value>{translate key="default.pressSettings.emailSignature"}</value>
	</setting>
	<setting type="string" locale="1">
		<name>readerInformation</name>
		<value>{translate key="default.pressSettings.forReaders"}</value>
	</setting>
	<setting type="string" locale="1">
		<name>authorInformation</name>
		<value>{translate key="default.pressSettings.forAuthors"}</value>
	</setting>
	<setting type="string" locale="1">
		<name>librarianInformation</name>
		<value>{translate key="default.pressSettings.forLibrarians"}</value>
	</setting>
	<setting type="object" locale="0">
		<name>supportedFormLocales</name>
		<value>
			<array>
				<element>{$primaryLocale}</element>
			</array>
		</value>
	</setting>
	<setting type="object" locale="0">
		<name>supportedSubmissionLocales</name>
		<value>
			<array>
				<element>{$primaryLocale}</element>
			</array>
		</value>
	</setting>
	<setting type="object" locale="1">
		<name>submissionChecklist</name>
		<value>
			<array>
				<element>
					<array>
						<element key="content">{translate key="default.pressSettings.checklist.notPreviouslyPublished"}</element>
						<element key="order">1</element>
					</array>
				</element>
				<element>
					<array>
						<element key="content">{translate key="default.pressSettings.checklist.fileFormat"}</element>
						<element key="order">2</element>
					</array>
				</element>
				<element>
					<array>
						<element key="content">{translate key="default.pressSettings.checklist.addressesLinked"}</element>
						<element key="order">3</element>
					</array>
				</element>
				<element>
					<array>
						<element key="content">{translate key="default.pressSettings.checklist.submissionAppearance"}</element>
						<element key="order">4</element>
					</array>
				</element>
				<element>
					<array>
						<element key="content">{translate key="default.pressSettings.checklist.bibliographicRequirements"}</element>
						<element key="order">5</element>
					</array>
				</element>
			</array>
		</value>
	</setting>
	<setting type="object" locale="1">
		<name>cataloguingMetadata</name>
		<value>
			<array>
				<element key="name">{translate key="default.pressSettings.manager.setup.category"}</element>
				<element key="name">{translate key="default.pressSettings.manager.series.book"}</element>
				<element key="name">{translate key="common.keywords"}</element>
			</array>
		</value>
	</setting>
	<setting type="string" locale="0">
		<name>paymentPluginName</name>
		<value>ManualPayment</value>
	</setting>
	<setting type="string" locale="0">
		<name>currency</name>
		<value>CAD</value>
	</setting>
	<setting type="string" locale="0">
		<name>themePluginPath</name>
		<value>default</value>
	</setting>
	<setting type="bool" locale="0">
		<name>typeEnabledSubmission</name>
		<value>1</value>
	</setting>
	<setting type="bool" locale="0">
		<name>typeEnabledWorkflow</name>
		<value>1</value>
	</setting>
	<setting type="bool" locale="0">
		<name>keywordsEnabledSubmission</name>
		<value>1</value>
	</setting>
	<setting type="bool" locale="0">
		<name>keywordsEnabledWorkflow</name>
		<value>1</value>
	</setting>
</press_settings>
