=== jmvezic/morepress/books/lib/pkp/dtd/currencies.dtd
<!--
  * dtd/currencies.dtd
  *
  * Copyright (c) 2014-2018 Simon Fraser University
  * Copyright (c) 2000-2018 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * DTD for currency localization definitions.
  *
  -->

<!ELEMENT currencies (currency+)>
	<!ATTLIST currencies
		locale CDATA #REQUIRED>
<!ELEMENT currency EMPTY>
	<!ATTLIST currency
		code_alpha CDATA #REQUIRED
		code_numeric CDATA #REQUIRED
		name CDATA #REQUIRED>

=== jmvezic/morepress/books/lib/pkp/locale/sl_SI/currencies.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE currencies SYSTEM "../../dtd/currencies.dtd">

<!--
  * locale/sl_SI/currencies.xml
  *
  * Copyright (c) 2014-2018 Simon Fraser University
  * Copyright (c) 2000-2018 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Currencies data XML file. Based on ISO 4217:2015.
  -->

<currencies locale="sl_SI">
	<currency name="Ameriški dolar" code_alpha="USD" code_numeric="840" />
	<currency name="Evro" code_alpha="EUR" code_numeric="978" />
	<currency name="Kanadski dolar" code_alpha="CAD" code_numeric="124" />
	<currency name="Dirham ZAE" code_alpha="AED" code_numeric="784" />
	<currency name="Afgani" code_alpha="AFN" code_numeric="971" />
	<currency name="Lek" code_alpha="ALL" code_numeric="008" />
	<currency name="Armenski dram" code_alpha="AMD" code_numeric="051" />
	<currency name="Nizozemski antilski gulden" code_alpha="ANG" code_numeric="532" />
	<currency name="Kvanza" code_alpha="AOA" code_numeric="973" />
	<currency name="Argentinski peso" code_alpha="ARS" code_numeric="032" />
	<currency name="Avstralski dolar" code_alpha="AUD" code_numeric="036" />
	<currency name="Arubski florin" code_alpha="AWG" code_numeric="533" />
	<currency name="Azerbajdžanski manat" code_alpha="AZN" code_numeric="944" />
	<currency name="Konvertibilna marka" code_alpha="BAM" code_numeric="977" />
	<currency name="Barbadoški dolar" code_alpha="BBD" code_numeric="052" />
	<currency name="Taka" code_alpha="BDT" code_numeric="050" />
	<currency name="Bolgarski lev" code_alpha="BGN" code_numeric="975" />
	<currency name="Bahrajnski dinar" code_alpha="BHD" code_numeric="048" />
	<currency name="Burundijski frank" code_alpha="BIF" code_numeric="108" />
	<currency name="Bermudski dolar" code_alpha="BMD" code_numeric="060" />
	<currency name="Brunejski dolar" code_alpha="BND" code_numeric="096" />
	<currency name="Boliviano" code_alpha="BOB" code_numeric="068" />
	<currency name="Brazilski real" code_alpha="BRL" code_numeric="986" />
	<currency name="Bahamski dolar" code_alpha="BSD" code_numeric="044" />
	<currency name="Ngultrum" code_alpha="BTN" code_numeric="064" />
	<currency name="Pula" code_alpha="BWP" code_numeric="072" />
	<currency name="Beloruski rubelj" code_alpha="BYN" code_numeric="933" />
	<currency name="Belizejski dolar" code_alpha="BZD" code_numeric="084" />
	<currency name="Kongoški frank" code_alpha="CDF" code_numeric="976" />
	<currency name="Švicarski frank" code_alpha="CHF" code_numeric="756" />
	<currency name="Čilski peso" code_alpha="CLP" code_numeric="152" />
	<currency name="Kitajski juan" code_alpha="CNY" code_numeric="156" />
	<currency name="Kolumbijski peso" code_alpha="COP" code_numeric="170" />
	<currency name="Kostariški kolon" code_alpha="CRC" code_numeric="188" />
	<currency name="Kubanski peso" code_alpha="CUP" code_numeric="192" />
	<currency name="Konvertibilni peso" code_alpha="CUC" code_numeric="931" />
	<currency name="Zelenortski eskudo" code_alpha="CVE" code_numeric="132" />
	<currency name="Češka krona" code_alpha="CZK" code_numeric="203" />
	<currency name="Džibutski frank" code_alpha="DJF" code_numeric="262" />
	<currency name="Danska krona" code_alpha="DKK" code_numeric="208" />
	<currency name="Dominikanski peso" code_alpha="DOP" code_numeric="214" />
	<currency name="Alžirski dinar" code_alpha="DZD" code_numeric="012" />
	<currency name="Egiptovski funt" code_alpha="EGP" code_numeric="818" />
	<currency name="Nakfa" code_alpha="ERN" code_numeric="232" />
	<currency name="Etiopski bir" code_alpha="ETB" code_numeric="230" />
	<currency name="Fidžijski dolar" code_alpha="FJD" code_numeric="242" />
	<currency name="Falklandski funt" code_alpha="FKP" code_numeric="238" />
	<currency name="Funt šterling" code_alpha="GBP" code_numeric="826" />
	<currency name="Lari" code_alpha="GEL" code_numeric="981" />
	<currency name="Ganski novi cedi" code_alpha="GHS" code_numeric="936" />
	<currency name="Gibraltarski funt" code_alpha="GIP" code_numeric="292" />
	<currency name="Dalasi" code_alpha="GMD" code_numeric="270" />
	<currency name="Gvinejski frank" code_alpha="GNF" code_numeric="324" />
	<currency name="Kecal" code_alpha="GTQ" code_numeric="320" />
	<currency name="Gvajanski dolar" code_alpha="GYD" code_numeric="328" />
	<currency name="Hongkonški dolar" code_alpha="HKD" code_numeric="344" />
	<currency name="Lempira" code_alpha="HNL" code_numeric="340" />
	<currency name="Kuna" code_alpha="HRK" code_numeric="191" />
	<currency name="Gurd" code_alpha="HTG" code_numeric="332" />
	<currency name="Forint" code_alpha="HUF" code_numeric="348" />
	<currency name="Rupija" code_alpha="IDR" code_numeric="360" />
	<currency name="Izraelski šekel" code_alpha="ILS" code_numeric="376" />
	<currency name="Indijska rupija" code_alpha="INR" code_numeric="356" />
	<currency name="Iraški dinar" code_alpha="IQD" code_numeric="368" />
	<currency name="Iranski rial" code_alpha="IRR" code_numeric="364" />
	<currency name="Islandska krona" code_alpha="ISK" code_numeric="352" />
	<currency name="Jamajški dolar" code_alpha="JMD" code_numeric="388" />
	<currency name="Jordanski dinar" code_alpha="JOD" code_numeric="400" />
	<currency name="Jen" code_alpha="JPY" code_numeric="392" />
	<currency name="Kenijski šiling" code_alpha="KES" code_numeric="404" />
	<currency name="Som" code_alpha="KGS" code_numeric="417" />
	<currency name="Riel" code_alpha="KHR" code_numeric="116" />
	<currency name="Komorski frank" code_alpha="KMF" code_numeric="174" />
	<currency name="Severnokorejski von" code_alpha="KPW" code_numeric="408" />
	<currency name="Von" code_alpha="KRW" code_numeric="410" />
	<currency name="Kuvajtski dinar" code_alpha="KWD" code_numeric="414" />
	<currency name="Kajmanski dolar" code_alpha="KYD" code_numeric="136" />
	<currency name="Tenge" code_alpha="KZT" code_numeric="398" />
	<currency name="Kip" code_alpha="LAK" code_numeric="418" />
	<currency name="Libanonski funt" code_alpha="LBP" code_numeric="422" />
	<currency name="Šrilanška rupija" code_alpha="LKR" code_numeric="144" />
	<currency name="Liberijski dolar" code_alpha="LRD" code_numeric="430" />
	<currency name="Loti" code_alpha="LSL" code_numeric="426" />
	<currency name="Libijski dinar" code_alpha="LYD" code_numeric="434" />
	<currency name="Maroški dirham" code_alpha="MAD" code_numeric="504" />
	<currency name="Moldavski leu" code_alpha="MDL" code_numeric="498" />
	<currency name="Madagaskarski ariary" code_alpha="MGA" code_numeric="969" />
	<currency name="Denar" code_alpha="MKD" code_numeric="807" />
	<currency name="Kiat" code_alpha="MMK" code_numeric="104" />
	<currency name="Tugrik" code_alpha="MNT" code_numeric="496" />
	<currency name="Pataka" code_alpha="MOP" code_numeric="446" />
	<currency name="Uguija" code_alpha="MRO" code_numeric="478" />
	<currency name="Mauricijska rupija" code_alpha="MUR" code_numeric="480" />
	<currency name="Rufija" code_alpha="MVR" code_numeric="462" />
	<currency name="Malavijska kvača" code_alpha="MWK" code_numeric="454" />
	<currency name="Mehiški peso" code_alpha="MXN" code_numeric="484" />
	<currency name="Malezijski ringgit" code_alpha="MYR" code_numeric="458" />
	<currency name="Mozambiški metikal" code_alpha="MZN" code_numeric="943" />
	<currency name="Namibijski dolar" code_alpha="NAD" code_numeric="516" />
	<currency name="Naira" code_alpha="NGN" code_numeric="566" />
	<currency name="Nikaragovska kordova" code_alpha="NIO" code_numeric="558" />
	<currency name="Norveška krona" code_alpha="NOK" code_numeric="578" />
	<currency name="Nepalska rupija" code_alpha="NPR" code_numeric="524" />
	<currency name="Novozelandski dolar" code_alpha="NZD" code_numeric="554" />
	<currency name="Omanski rial" code_alpha="OMR" code_numeric="512" />
	<currency name="Balboa" code_alpha="PAB" code_numeric="590" />
	<currency name="Sol" code_alpha="PEN" code_numeric="604" />
	<currency name="Kina" code_alpha="PGK" code_numeric="598" />
	<currency name="Filipinski peso" code_alpha="PHP" code_numeric="608" />
	<currency name="Pakistanska rupija" code_alpha="PKR" code_numeric="586" />
	<currency name="Zlot" code_alpha="PLN" code_numeric="985" />
	<currency name="Gvaran" code_alpha="PYG" code_numeric="600" />
	<currency name="Katarski rial" code_alpha="QAR" code_numeric="634" />
	<currency name="Romunski leu" code_alpha="RON" code_numeric="946" />
	<currency name="Srbski dinar" code_alpha="RSD" code_numeric="941" />
	<currency name="Ruski rubelj" code_alpha="RUB" code_numeric="643" />
	<currency name="Ruandski frank" code_alpha="RWF" code_numeric="646" />
	<currency name="Saudski rial" code_alpha="SAR" code_numeric="682" />
	<currency name="Salvadorski kolon" code_alpha="SVC" code_numeric="222" />
	<currency name="Salomonovotoški dolar" code_alpha="SBD" code_numeric="090" />
	<currency name="Sejšelska rupija" code_alpha="SCR" code_numeric="690" />
	<currency name="Sudanski funt" code_alpha="SDG" code_numeric="938" />
	<currency name="Južnosudanski funt" code_alpha="SSP" code_numeric="728" />
	<currency name="Švedska krona" code_alpha="SEK" code_numeric="752" />
	<currency name="Singapurski dolar" code_alpha="SGD" code_numeric="702" />
	<currency name="Svetohelenski funt" code_alpha="SHP" code_numeric="654" />
	<currency name="Leone" code_alpha="SLL" code_numeric="694" />
	<currency name="Somalski šiling" code_alpha="SOS" code_numeric="706" />
	<currency name="Surinamski dolar" code_alpha="SRD" code_numeric="968" />
	<currency name="Dobra" code_alpha="STD" code_numeric="678" />
	<currency name="Sirski funt" code_alpha="SYP" code_numeric="760" />
	<currency name="Lilangeni" code_alpha="SZL" code_numeric="748" />
	<currency name="Baht" code_alpha="THB" code_numeric="764" />
	<currency name="Somoni" code_alpha="TJS" code_numeric="972" />
	<currency name="Turkmenski manat" code_alpha="TMT" code_numeric="934" />
	<currency name="Tunizijski dinar" code_alpha="TND" code_numeric="788" />
